// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqgqqijucxepfnrnxjjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZ3FxaWp1Y3hlcGZucm54amptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDIzMDAsImV4cCI6MjA1OTU3ODMwMH0.3KOtxvujBKfnA4KXnioFN7y-MG0B1a13S-Bh7u4lwWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);